### ISSUE TITLE
Could not install zip/unzip/sshpass packages

### ISSUE THREAD

**Issue by abessifi** [imad-bouhamidi/vagrant-docker-jenkins-jhipster#1]
I "vagrant up" the virtual machine and got this error messages during packages installation :

==> default: ======= Installing Zip & Unzip ======
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: Package zip is not available, but is referred to by another package.
==> default: This may mean that the package is missing, has been obsoleted, or
==> default: is only available from another source
==> default: E
==> default: : 
==> default: Package 'zip' has no installation candidate
==> default: ======= Installing sshpass ======
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following NEW packages will be installed:
==> default:   sshpass
==> default: 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
==> default: Need to get 10.5 kB of archives.
==> default: After this operation, 56.3 kB of additional disk space will be used.
==> default: WARNING: The following packages cannot be authenticated!
==> default:   sshpass
==> default: Install these packages without verification?
==> default:  [y/N] 
==> default: E
==> default: : 
==> default: Some packages could not be authenticated
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by imad-bouhamidi** [comment]
@abessifi thank you for reporting that and fixing the problem.

**Comment by abessifi** [comment]
fixed https://github.com/imad-bouhamidi/vagrant-docker-jenkins-jhipster/pull/2

**Comment by abessifi** [comment]
fixed https://github.com/imad-bouhamidi/vagrant-docker-jenkins-jhipster/pull/2 .
